# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=500)),
                ('price', models.FloatField()),
                ('priority', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to=b'')),
                ('link', models.URLField()),
            ],
        ),
    ]
