# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 07:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wish', '0002_auto_20171102_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
