# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todoitem',
            options={'verbose_name': 'Todo Item'},
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='description',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='due_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='status',
            field=models.CharField(choices=[('done', 'done'), ('progress', 'in progress'), ('finished', 'finished')], max_length=30),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='urgency',
            field=models.CharField(choices=[('h', 'urgent'), ('m', 'moderately urgent'), ('l', 'not urgent')], max_length=20),
        ),
    ]
